#![feature(
    iter_array_chunks,
    decl_macro,
    ascii_char,
    debug_closure_helpers,
    ip,
    let_chains,

    doc_cfg
)]

pub mod packet;
pub mod value;
pub mod registry;
pub mod mojang;
pub mod autogenerated;

pub const MINECRAFT_VERSION : &'static str = "1.21.4";
pub const PROTOCOL_VERSION  : u32          = 769;
